dataset: pure_custom

#### datasets
datasets:
  train:
    dist: False
    root: ./dataset/pure_custom
    use_shuffle: true
    n_workers: 1  
    batch_size: 8
    use_flip: true
    use_crop: true
    patch_size: 96

  val:
    dist: False
    root: ./dataset/pure_custom
    n_workers: 1
    use_crop: true
    batch_size: 1 


